### ISSUE TITLE
Format the Event Issue Template Title and Bodies

### ISSUE THREAD

**Issue by anguspiv** [jsla/lunch.js#451]
Using the Issue Form Templates for creating Issue Events, we should be able to easily format and update the issue body and title from the information provided. 

Here is an example format I think should work for us

Issue Title:
```markdown
# Santa Monica - May 6, 2025
```
```markdown
<Neighborhood.name> - <Event.date>
```

Issue Body:
```markdown
# Santa Monica
## Tuesday, May 6 2025 at 12:30 PM
### @ [Vito's Pizza](https://vitossm.com/)

**Address**
2455 Santa Monica Blvd
Santa Monica, CA 90404

**Championed by**:
- Angus Perkerson @anguspiv

Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus ex sapien vitae pellentesque sem placerat. In id cursus mi pretium tellus duis convallis. Tempus leo eu aenean sed diam urna tempor. Pulvinar vivamus fringilla lacus nec metus bibendum egestas. Iaculis massa nisl malesuada lacinia integer nunc posuere. Ut hendrerit semper vel class aptent taciti sociosqu. Ad litora torquent per conubia nostra inceptos himenaeos.

If you are planning to attend subscribe to the issue to get notifications for new comments.

As a reminder, Lunch.js events follow the [JS.LA Code of Conduct](https://js.la/code-of-conduct)
Please let your champion know,
or reach out to [Angus Perkerson](mailto:angusp@angusp.com)
or any [JS.LA Team Member](https://js.la/team) for any violation or incident,
and we will take appropriate actions.
```
```markdown
# <Neighborhood.name>
## <Event.date | "Tuesday, May 6 2025 at 12:30 PM">
### @ [<Event.location.name>](event.location.url)

**Address**
<Event.location.address.street[0]>
<Event.location.address.street[1]>
<Event.location.address.city>, <Event.location.address.state> <Event.location.address.postal>

**Championed by**:
- <Event.champions[i].name> <Event.champions[i].username>

<Event.description>

If you are planning to attend subscribe to the issue to get notifications for new comments.

As a reminder, Lunch.js events follow the [JS.LA Code of Conduct](https://js.la/code-of-conduct)
Please let your champion know,
or reach out to [Angus Perkerson](mailto:angusp@angusp.com)
or any [JS.LA Team Member](https://js.la/team) for any violation or incident,
and we will take appropriate actions.
```

**Comment by anguspiv** [comment]
For context I noted down some of the data fields and schemas while thinking about this. Thought it might help to have around

## Glossary

**Neighborhood** - A small hyper local area of Los Angeles that serves members of that area. 

**Event** - An recurring date and time that members of a neighborhood can attend in person to meet and chat with each other

**Location** - The physical place for an event for members to meet

**Champion** - The volunteer(s) who manage a Lunch.js event.

## Schema

```yaml
Champion: // should be the github issue assignee
  username: @anguspiv // required
  name: Angus Perkerson // required


Location
  name: "Vito's Pizza" // required
  url: https://vitossm.com/
  address: // required
    street:
        - 2455 Santa Monica Blvd. // required
        - Suite 200 // optional
    city: Santa Monica // required
    state: CA // required
    postal: 90404 // required

Event:
  date: May 6, 2025 12:30 PM  // required
  champions:
    - <Champion>
  location: <Location>
  description: Blah blah blah blah blah blah

Neighborhood:
  name: "Santa Monica" // required
  neighborhoods: // See  [Los Angeles Neighborhoods and Communities of Southern California - Google My Maps](https://www.google.com/maps/d/u/0/viewer?mid=15x_g-cPFp0OczIjhyVOEOLqtQMw&femb=1&ll=34.134052740081444,-118.39639229231445&z=10)
  
    - Santa Monica
    - Wilshire Montana
    - Ocean Park
    - North of Montana
   champions:
     - <Champion>
   events:
     - <event>
      
```
